server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: store-collaboration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/store_cop

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.tlm.storecollab.controller

# 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: https://store-collab-1311433795.cos.ap-guangzhou.myqcloud.com
    secretId: AKIDT0b6g8Rgpx1va2HI6g9OC2g6ITTGtLac
    secretKey: 397wtxsZ4MRKzQOGvNceU7ZoqiMn02xf
    region: ap-guangzhou
    bucket: store-collab-1311433795