server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: store-collaboration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/store-collab

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0