server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000

spring:
  application:
    name: store-collaboration
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/store_cop
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000
  session:
    store-type: redis
    timeout: 2592000

mybatis-plus:
  configuration:
    # MyBatis 配置
    map-underscore-to-camel-case: false
  global-config:
    # 全局配置
    db-config:
      # 数据库配置
      id-type: auto
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0

knife4j:
  enable: true
  openapi:
    title: 接口文档
    version: 1.0
    group:
      test1:
        group-name: 分组名称
        api-rule: package
        api-rule-resources:
          - com.tlm.storecollab.controller



## 对象存储配置（需要从腾讯云获取）
#cos:
#  client:
#    host: xxx
#    secretId: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx

## 阿里云百炼大模型
#aLiYun:
#  secret: xxx

