package com.tlm.storecollab.api.aliyunapi.model;

import com.fasterxml.jackson.annotation.JsonProperty;
import lombok.Data;
import cn.hutool.json.JSONUtil;
import cn.hutool.core.annotation.Alias;

/**
 * 图像外绘任务请求对象。
 */
@Data
public class CreateOutPaintingTaskRequest {

    /**
     * 模型名称。示例值："image-out-painting"。
     */
    private String model;

    /**
     * 输入图像信息。
     */
    private Input input = new Input();

    /**
     * 输出图像处理参数。
     */
    private Parameters parameters = new Parameters();

    /**
     * 将当前对象序列化为JSON字符串（字段别名生效）。
     */
    public String toJson() {
        return JSONUtil.toJsonStr(this);
    }

    /**
     * 输入图像的基本信息。
     */
    @Data
    public static class Input {

        /**
         * 图像URL地址或者图像base64数据。
         *
         * 图像格式：JPG、JPEG、PNG、HEIF、WEBP。
         * 图像大小：不超过10MB。
         * 图像分辨率：不低于512×512像素且不超过4096×4096像素。
         * 图像单边长度范围：[512, 4096]，单位像素。
         */
        @Alias("image_url")
        private String imageUrl;
    }

    /**
     * 设置输出图像的处理参数。
     */
    @Data
    public static class Parameters {

        /**
         * 逆时针旋转角度。默认值为0，取值范围[0, 359]，单位为度。
         */
        private Integer angle;

        /**
         * 图像宽高比。可选值有["", "1:1", "3:4", "4:3", "9:16", "16:9"]。
         * 默认值为""，表示不设置输出图像的宽高比。
         */
        @Alias("output_ratio")
        private String outputRatio;

        /**
         * 图像居中，在水平方向上按比例扩展图像。
         * 默认值为1.0，取值范围[1.0, 3.0]。
         */
        @Alias("x_scale")
        @JsonProperty("x_scale")
        private Float xScale;

        /**
         * 图像居中，在垂直方向上按比例扩展图像。
         * 默认值为1.0，取值范围[1.0, 3.0]。
         */
        @Alias("y_scale")
        @JsonProperty("y_scale")
        private Float yScale;

        /**
         * 在图像上方添加像素。
         * 默认值为0，取值限制 top_offset + bottom_offset < 3 × 输入图像高度。
         */
        @Alias("top_offset")
        private Integer topOffset;

        /**
         * 在图像下方添加像素。
         * 默认值为0，取值限制 top_offset + bottom_offset < 3 × 输入图像高度。
         */
        @Alias("bottom_offset")
        private Integer bottomOffset;

        /**
         * 在图像左侧添加像素。
         * 默认值为0，取值限制 left_offset + right_offset < 3 × 输入图像宽度。
         */
        @Alias("left_offset")
        private Integer leftOffset;

        /**
         * 在图像右侧添加像素。
         * 默认值为0，取值限制 left_offset + right_offset < 3 × 输入图像宽度。
         */
        @Alias("right_offset")
        private Integer rightOffset;

        /**
         * 开启图像最佳质量模式。
         * 默认值为false，减少图像生成的等待时间。
         * 如果需要更多图像细节，可以设置为true，但耗时会成倍增加。
         */
        @Alias("best_quality")
        private Boolean bestQuality;

        /**
         * 限制模型生成的图像文件大小。
         * 默认值为true：
         * - 当输入图像单边长度 <= 10000 时，输出图像文件大小在5MB以下；
         * - 当输入图像单边长度 > 10000 时，输出图像文件大小在10MB以下。
         * 输出图像的长宽比范围为1:4至4:1。
         */
        @Alias("limit_image_size")
        private Boolean limitImageSize;

        /**
         * 添加Generated by AI水印。
         * 默认值为true，在输出图像左下角处添加水印。
         */
        @Alias("add_watermark")
        private Boolean addWatermark;
    }
}